name: Pulumi Preview PR
on:
- pull_request
jobs:
  preview:
    if: github.actor != 'dependabot[bot]'
    name: Preview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - run: npm install
    - uses: pulumi/actions@v2
      with:
        command: preview
        stack-name: prod
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
